### ISSUE TITLE
Client - Exception caught during firing event net.minecraftforge.client.event.ClientChatReceivedEvent@29c7dd74:

### ISSUE THREAD

**Issue by ProsperCraft** [elifoster/Ping#17] opened 2018-03-26 17:52 UTC
https://gist.github.com/ProsperCraft/c66618a6f7d111d8295dcf4f204de53d

project maintainer edit in case that gist disappears:
```
11:49:47] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] <owen_pi> Hi Goshen
[11:49:47] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] jonah_pi has made the advancement [Shield Wall]
[11:49:47] [main/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.ClientChatReceivedEvent@29c7dd74:
java.lang.IllegalArgumentException: value already present: santa.ping.PingSound@156b88a2
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:287) ~[guava-21.0.jar:?]
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:262) ~[guava-21.0.jar:?]
	at net.minecraft.client.audio.SoundManager.func_148611_c(SoundManager.java:430) ~[chm.class:?]
	at net.minecraft.client.audio.SoundHandler.func_147682_a(SoundHandler.java:258) ~[cho.class:?]
	at santa.ping.PingEventHandler.playSoundSendMessage$1(PingEventHandler.scala:16) ~[PingEventHandler.class:?]
	at santa.ping.PingEventHandler.onChatMessage(PingEventHandler.scala:31) ~[PingEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1288_PingEventHandler_onChatMessage_ClientChatReceivedEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onClientChat(ForgeEventFactory.java:394) [ForgeEventFactory.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147251_a(NetHandlerPlayClient.java:843) [brz.class:?]
	at net.minecraft.network.play.server.SPacketChat.func_148833_a(SourceFile:41) [in.class:?]
	at net.minecraft.network.play.server.SPacketChat.func_148833_a(SourceFile:10) [in.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[11:49:47] [main/ERROR] [FML]: Index: 1 Listeners:
[11:49:47] [main/ERROR] [FML]: 0: NORMAL
[11:49:47] [main/ERROR] [FML]: 1: ASM: santa.ping.PingEventHandler@6db608d9 onChatMessage(Lnet/minecraftforge/client/event/ClientChatReceivedEvent;)V
[11:49:47] [main/FATAL] [net.minecraft.client.Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: value already present: santa.ping.PingSound@156b88a2
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalArgumentException: value already present: santa.ping.PingSound@156b88a2
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:287) ~[guava-21.0.jar:?]
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:262) ~[guava-21.0.jar:?]
	at net.minecraft.client.audio.SoundManager.func_148611_c(SoundManager.java:430) ~[chm.class:?]
	at net.minecraft.client.audio.SoundHandler.func_147682_a(SoundHandler.java:258) ~[cho.class:?]
	at santa.ping.PingEventHandler.playSoundSendMessage$1(PingEventHandler.scala:16) ~[PingEventHandler.class:?]
	at santa.ping.PingEventHandler.onChatMessage(PingEventHandler.scala:31) ~[PingEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1288_PingEventHandler_onChatMessage_ClientChatReceivedEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onClientChat(ForgeEventFactory.java:394) ~[ForgeEventFactory.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147251_a(NetHandlerPlayClient.java:843) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketChat.func_148833_a(SourceFile:41) ~[in.class:?]
	at net.minecraft.network.play.server.SPacketChat.func_148833_a(SourceFile:10) ~[in.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
[11:49:47] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] <owen_pi> are you mining below ground?
[11:50:17] [main/INFO] [FML]: Applying holder lookups
[11:50:17] [main/INFO] [FML]: Holder lookups applied

```

**Comment by elifoster** [comment] 2018-03-26 18:10
Duplicate of #7

**Closed as completed by elifoster** 2018-03-26 18:10 UTC
Labels: duplicate
