### ISSUE TITLE
Client CEE - concurrent.ExecutionException: java.lang.IllegalArgumentException: value already present: santa.ping.PingSound@faf9fc3

### ISSUE THREAD

**Issue by ProsperCraft** [elifoster/Ping#18] opened 2018-05-21 21:07 UTC
https://paste.dimdev.org/uqubojubir.txt

VanillaFix produced this not long after I installed it, said I should report it, but it wasn't really a crash.

**Comment by elifoster** [comment] 2018-05-23 01:09
Duplicate of #7.

**Closed as completed by elifoster** 2018-05-23 01:09 UTC
Labels: duplicate, 1.9
